"""Python SERVER-skeleton emitter for the Picomesh msgpack frontend.

The mirror of emit_python.py (client): instead of a client that calls INTO a
picomesh msgpack frontend, this emits a foreign Python service that SPEAKS the
Picomesh msgpack envelope, so a picomesh C process can call OUT to it
(`--transport msgpack`, or a configured `transport: msgpack` remote).

The generated base class owns everything that is protocol, not business logic:
length-prefixed framing, envelope validation per docs/msgpack-rpc.md (v1 is
positional-only — non-empty `kwargs` is rejected), `op` dispatch (`invoke` +
`describe`), structured error envelopes, and the serve loop. The developer
subclasses it and implements one typed handler per method — each stub raises
NotImplementedError until filled in."""

GEN_NOTE = "# AUTO-GENERATED by tools/msgpack-codegen — do not edit.\n"

_TEMPLATE = '''<<GEN_NOTE>>"""Generated msgpack SERVER skeleton for `<<MODULE>>`. Requires `msgpack` (pip).

Subclass `<<CLS>>` and implement each handler, then `.serve(host, port)`:

    class MyService(<<CLS>>):
        def <<EXAMPLE_SLOT>>(self, <<EXAMPLE_ARGS>>):
            return ...

    MyService().serve("127.0.0.1", 7900)
"""
import socket
import struct

import msgpack


def _recv_exact(conn, n):
    buf = bytearray()
    while len(buf) < n:
        chunk = conn.recv(n - len(buf))
        if not chunk:
            return None
        buf += chunk
    return bytes(buf)


class <<CLS>>:
    """Base skeleton for a foreign `<<MODULE>>` service. Speaks the Picomesh
    MessagePack envelope (u32 BE length frame + msgpack map), strict serial
    request/response. Override the handler methods below."""

    # path -> (handler attribute name, [param names]).
    _METHODS = {
<<METHOD_TABLE>>    }
    # path -> [{"name":..., "type":...}] for `op: describe`.
    _DESCRIBE = {
<<DESCRIBE_TABLE>>    }

    @staticmethod
    def _ok(result):
        return {"v": 1, "ok": True, "result": result}

    @staticmethod
    def _err(code, message):
        return {"v": 1, "ok": False, "error": {"message": message, "code": code}}

    def _dispatch(self, env):
        if not isinstance(env, dict):
            return self._err("bad_envelope", "envelope is not a map")
        # v1 is positional-only: a non-empty kwargs is rejected for every op,
        # never silently ignored (docs/msgpack-rpc.md).
        if env.get("kwargs"):
            return self._err("kwargs_unsupported",
                             "msgpack v1 binds positional args only; kwargs must be empty")
        op = env.get("op", "invoke")
        path = env.get("path", "")
        if not path:
            return self._err("bad_path", "missing 'path'")
        if op == "describe":
            params = self._DESCRIBE.get(path)
            if params is None:
                return self._err("no_such_method", "describe: unknown method %s" % path)
            return self._ok({"path": path, "params": params})
        if op != "invoke":
            return self._err("bad_op", "unsupported op %s" % op)
        spec = self._METHODS.get(path)
        if spec is None:
            return self._err("no_such_method", "no method %s" % path)
        handler_name, param_names = spec
        args = env.get("args", [])
        if not isinstance(args, list):
            return self._err("bad_envelope", "'args' is not an array")
        if len(args) != len(param_names):
            return self._err("call_error",
                             "%s expects %d arg(s), got %d" % (path, len(param_names), len(args)))
        try:
            result = getattr(self, handler_name)(*args)
        except NotImplementedError:
            return self._err("not_implemented", "%s is not implemented" % path)
        except Exception as exc:  # noqa: BLE001 — reflect any handler failure
            return self._err("call_error", str(exc))
        return self._ok(result)

    def serve(self, host="127.0.0.1", port=7900):
        srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind((host, port))
        srv.listen(8)
        while True:
            conn, _ = srv.accept()
            with conn:
                while True:
                    hdr = _recv_exact(conn, 4)
                    if not hdr:
                        break
                    (n,) = struct.unpack(">I", hdr)
                    body = _recv_exact(conn, n)
                    if body is None:
                        break
                    env = msgpack.unpackb(body, raw=False)
                    resp = msgpack.packb(self._dispatch(env), use_bin_type=True)
                    conn.sendall(struct.pack(">I", len(resp)) + resp)

<<BODY>>'''


def _class_name(module: str) -> str:
    return "".join(p.capitalize() for p in module.replace("-", "_").split("_")) + "Server"


# Neutral kind -> a Python type-hint string, for the generated handler stubs.
_HINT = {"int": "int", "uint": "int", "float": "float", "str": "str"}


def emit(module: str, methods: list) -> tuple:
    method_rows = []
    describe_rows = []
    handlers = []
    for m in methods:
        names = [a["name"] for a in m["args"]]
        method_rows.append("        %r: (%r, %r),\n" % (m["path"], m["slot"], names))
        params = [{"name": a["name"], "type": a["ctype"]} for a in m["args"]]
        describe_rows.append("        %r: %r,\n" % (m["path"], params))
        hinted = ", ".join("%s: %s" % (a["name"], _HINT.get(a["kind"], "object")) for a in m["args"])
        sig = ", ".join(["self"] + ([hinted] if hinted else []))
        handlers.append("    def %s(%s):\n"
                        "        \"\"\"%s — implement me.\"\"\"\n"
                        "        raise NotImplementedError(%r)\n"
                        % (m["slot"], sig, m["path"], m["path"]))
    body = "\n".join(handlers) if handlers else "    pass\n"
    example = methods[0] if methods else None
    example_slot = example["slot"] if example else "method"
    example_args = ", ".join(a["name"] for a in example["args"]) if example else ""
    text = (_TEMPLATE
            .replace("<<GEN_NOTE>>", GEN_NOTE)
            .replace("<<MODULE>>", module)
            .replace("<<CLS>>", _class_name(module))
            .replace("<<EXAMPLE_SLOT>>", example_slot)
            .replace("<<EXAMPLE_ARGS>>", example_args)
            .replace("<<METHOD_TABLE>>", "".join(method_rows))
            .replace("<<DESCRIBE_TABLE>>", "".join(describe_rows))
            .replace("<<BODY>>", body))
    return text, f"{module}_server.py"
